language: php
php:
  - 7.1
  - 7.2
  - 7.3
script:
  - phpunit -c tests/phpunit.xml --coverage-clover=coverage.clover
before_script:
  - composer install
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover